
name: TabooSK

description: the Skript addons

authors: [坏黑]
website: http://www.15imc.com/index.html

main: me.skymc.skaddon.taboosk.TabooSK

version: 1.1

depend: [Skript]
soft-depend: [PlaceholderAPI]

commands:
  taboosk: